package modules

var (
	ERR_WRONG_VERSION             = "ERR_WRONG_VERSION"
	ERR_TYPE_NOT_SUPPORTED        = "ERR_TYPE_NOT_SUPPORTED"
	ERR_CHAIN_NOT_SUPPORTED       = "ERR_CHAIN_NOT_SUPPORTED"
	ERR_CLIENT_UUID_NOT_GENERATED = "ERR_CLIENT_UUID_NOT_GENERATED"
	ERR_ACTION_NOT_SUPPORTED      = "ERR_ACTION_NOT_SUPPORTED"
	ERR_UNDEFINED                 = "ERR_UNDEFINED"

	ACTION_REGISTER = "0"
	ACTION_LOGIN    = "1"

	SYS_VER           = "1.0"
	TYPE_CLIENT_HELLO = "ClientHello"
	TYPE_SERVER_HELLO = "ServerHello"
)
